<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="AdminPanel.aspx.cs" Inherits="TweeterConnect.AdminPanel" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <h1>Admin Panel</h1>
        <asp:Label ID="Message" runat="server" Text="Loading"></asp:Label>
        <asp:GridView ID="editUsers" runat="server"
            AutoGenerateDeleteButton="true"
            AutoGenerateColumns="true"
            EnableViewState="false"
            OnRowDeleting="RowDelete"
            >
        </asp:GridView>
        <br />
        <asp:Button ID="btnLogout" runat="server" Text="Logout" OnClick="Logout_Click"/>
    </div>
    </form>
</body>
</html>
